version: '3'
services:
  currency:
    container_name: deals-updater
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python main.py
    deals:
      - deals-network
networks:
  deals-network:
    driver: bridge
